FROM maven:3.6.3-jdk-8

RUN git clone https://github.com/dvcama/LodView.git
WORKDIR LodView
RUN git reset --hard 46424e3217d5d60b778c3556c66abf3861914444
RUN mvn compile war:war

CMD ["mvn", "jetty:run"]